### ISSUE TITLE
Requirements file

### ISSUE THREAD

**Issue by benrudolph** [ieda-project/dashboard-v2#1]
Hey @gdeflaux, is there a way to specify a requirements file (similar to bundler in ruby)? Googled around a bit and it didn't seem super common, but i'm a total newb with R. feel free to close if not possible

**Comment by gdeflaux** [comment]
Hi,

Just found out about Packrat (https://rstudio.github.io/packrat/). If you create a new Project with RStudio you can initialize it. But I've never used it.

FYI, I updated R to v3.2.3 and all the libraries to their latest version and all seemed to work fine.

Cheers,

Gui
